services:
  mysql:
    image: mysql:8.0
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gestion_etudiants
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  tomcat:
    build: .
    container_name: student-tomcat
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./target/student-management.war:/usr/local/tomcat/webapps/ROOT.war

volumes:
  mysql-data:
